name: Telegram Bot Runner

on:
  push:
    branches: [ main ]  # يعمل عند رفع كود جديد لفرع main
  pull_request:
    branches: [ main ]
  workflow_dispatch:      # يتيح لك تشغيله يدوياً من GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot pymongo dnspython certifi

      - name: Run Bot
        env:
          # هنا نقوم بربط المتغيرات السرية (Secrets) التي سنضبطها في الإعدادات
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: python main.py
